[project]
name = "testfloat-lib"

[target.testfloat-lib]
type = "static"
sources = ["src/**.c", "include/**.h"]
include-directories = ["include"]
compile-definitions = ["HAVE_PLATFORM_H", "SOFTFLOAT_FAST_INT64", "EXTFLOAT80", "FLOAT64", "LONG_DOUBLE_IS_EXTFLOAT80"]
compile-options = ["/W0", "/MP", "/GL"]