[project]
name = "testfloat-pe"

[target.testfloat-pe]
type = "executable"
sources = ["main.c"]
include-directories = ["../testfloat-lib/include"]
compile-definitions = ["HAVE_PLATFORM_H", "SOFTFLOAT_FAST_INT64", "EXTFLOAT80", "FLOAT64", "LONG_DOUBLE_IS_EXTFLOAT80"]
link-libraries = ["testfloat-lib"]

cmake-before = """
# using /FORCE here because i dont care to fix linker issues LOL
add_link_options("/FORCE" "/DEBUG:FULL" "/LTCG")
add_compile_options("/O2" "/W0" "/MP" "/GL")

project(TestGenerator)
set(TEST_NAMES
    ui32_to_f32
    ui32_to_f64
    ui64_to_f32
    ui64_to_f64
    i32_to_f32
    i32_to_f64
    i64_to_f32
    i64_to_f64
    f32_to_f64
    f32_eq
    f32_le
    f32_lt
    f64_eq
    f64_le
    f64_lt
)

foreach(TEST_NAME ${TEST_NAMES})
    add_executable(${TEST_NAME} main_individual_tests.c)
	target_compile_definitions(${TEST_NAME} PRIVATE TESTFLOAT_TEST_NAME="${TEST_NAME}")
	target_include_directories(${TEST_NAME} PRIVATE "../testfloat-lib/include")
	target_link_libraries(${TEST_NAME} PUBLIC testfloat-lib)
endforeach()
"""